edition = "2021"
version = "Two"
tab_spaces = 4
use_small_heuristics = "Max"
max_width = 120
wrap_comments = true
comment_width = 120
format_code_in_doc_comments = true
doc_comment_code_block_width = 120
normalize_doc_attributes = true
imports_granularity = "Crate"
hex_literal_case = "Upper"
condense_wildcard_suffixes = true
use_try_shorthand = true
