name: Contracts CI

on:
  pull_request:
    paths:
      - 'packages/contracts/**/*.sol'

jobs:
  format:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/contracts
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Check Solidity formatting
        id: format
        run: make format_check
